# render.yaml

services:
  # Định nghĩa Web Service
  - type: web
    name: fastapi-recommender # Tên dịch vụ
    env: docker # Chỉ định môi trường là Docker
    plan: free # Sử dụng gói miễn phí

    # (Tùy chọn nhưng khuyến nghị) Cấu hình Health Check
    # Render sẽ gọi đến cổng 10000 bên trong container để kiểm tra
    healthCheckPath: /

    # Cài đặt tự động deploy
    autoDeploy: true
    branch: main
